# Generated by Django 3.1 on 2020-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=100, null=True)),
                ('star', models.FloatField(null=True)),
                ('movie_rating', models.CharField(max_length=100, null=True)),
                ('genre', models.CharField(max_length=100, null=True)),
                ('director', models.CharField(max_length=100, null=True)),
                ('actors', models.CharField(max_length=400, null=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
    ]
